### ISSUE TITLE
Not able to generate large size UDP packets

### ISSUE THREAD

**Issue by msidana** [pktgen/Pktgen-DPDK#151]
Hi,
I am using pktgen to generate large size packets 1800 bytes. These are my settings
```
root@server:~# cat /proc/net/pktgen/ens4 
Params: count 0  min_pkt_size: 1800  max_pkt_size: 1800
     frags: 0  delay: 3333  clone_skb: 0  ifname: ens4
     flows: 0 flowlen: 0
     queue_map_min: 0  queue_map_max: 0
     dst_min: 11.0.86.6  dst_max: 11.0.86.6
     src_min:   src_max: 
     src_mac: fa:16:3e:ad:c1:93 dst_mac: fa:16:3e:cb:27:93
     udp_src_min: 1000  udp_src_max: 1000  udp_dst_min: 1000  udp_dst_max: 1001
     src_mac_count: 0  dst_mac_count: 0
     Flags: IPDST_RND  
Current:
     pkts-sofar: 2992248  errors: 0
     started: 1809049280014us  stopped: 1809059253172us idle: 4065685us
     seq_num: 2992249  cur_dst_mac_offset: 0  cur_src_mac_offset: 0
     cur_saddr: 11.0.86.5  cur_daddr: 11.0.86.6
     cur_udp_dst: 1000  cur_udp_src: 1000
     cur_queue_map: 0
     flows: 0
Result: OK: 9973157(c5907472+d4065685) usec, 2992248 (1800byte,0frags)
  300030pps 4320Mb/sec (4320432000bps) errors: 0
root@server:~# 
```

While generating packets, I observed that no packets are showing up on tcpdump of the interface. Whereas with the same packet size iperf shows me the below error on the sending/receiving interface.
In both the cases, my sender and receiver are on different VMs.
``` 
UDP, bad length 1800 > 1472
```
Is there a constraint on the packet size in pktgen or am I missing something ?
